name: Build and Test

on:
    push: 
        branches: [main, develop]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
         - uses: actions/checkout@v4
    
         - name: Setup .Net
           uses: actions/setup-dotnet@v4
           with:
            dotnet-version: '8.0.x'

         - name: Restore dependencies
           run: dotnet restore

         - name: Build
           run: dotnet build --no-restore

         - name: Test
           run: dotnet test --no-build --verbosity normal

    publish:
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'

        steps:
        - uses: actions/checkout@v4
        - name: Setup .Net
          uses: actions/setup-dotnet@v4
          with:
             dotnet-version: '8.0.x'
        - name: Publish
          run: dotnet publish -c Release -o ./publish
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: calculator-app
            path: ./publish
  
